-- Item code mappings (from old/item_code_mapper.py)

INSERT OR REPLACE INTO item_code_mappings (financial_group, item_code, semantic_name, description_tr, statement_type, category) VALUES
('XI_29', '1Z', 'total_assets', 'Toplam Varlıklar / Aktif Toplamı', 'balance_sheet', 'asset'),
('XI_29', '1A', 'current_assets', 'Dönen Varlıklar', 'balance_sheet', 'asset'),
('XI_29', '1AA', 'cash_and_equivalents', 'Nakit ve Nakit Benzerleri', 'balance_sheet', 'asset'),
('XI_29', '1AB', 'marketable_securities', 'Menkul Kıymetler', 'balance_sheet', 'asset'),
('XI_29', '1AC', 'accounts_receivable', 'Ticari Alacaklar', 'balance_sheet', 'asset'),
('XI_29', '1AD', 'inventories', 'Stoklar', 'balance_sheet', 'asset'),
('XI_29', '1B', 'non_current_assets', 'Duran Varlıklar', 'balance_sheet', 'asset'),
('XI_29', '1BA', 'tangible_assets', 'Maddi Duran Varlıklar', 'balance_sheet', 'asset'),
('XI_29', '1BB', 'intangible_assets', 'Maddi Olmayan Duran Varlıklar', 'balance_sheet', 'asset'),
('XI_29', '2Z', 'total_liabilities_equity', 'Toplam Kaynaklar / Pasif Toplamı', 'balance_sheet', 'liability'),
('XI_29', '2A', 'current_liabilities', 'Kısa Vadeli Yükümlülükler', 'balance_sheet', 'liability'),
('XI_29', '2AA', 'short_term_borrowings', 'Finansal Borçlar (Kısa Vadeli)', 'balance_sheet', 'liability'),
('XI_29', '2AB', 'accounts_payable', 'Ticari Borçlar', 'balance_sheet', 'liability'),
('XI_29', '2B', 'non_current_liabilities', 'Uzun Vadeli Yükümlülükler', 'balance_sheet', 'liability'),
('XI_29', '2BA', 'long_term_borrowings', 'Finansal Borçlar (Uzun Vadeli)', 'balance_sheet', 'liability'),
('XI_29', '2N', 'shareholders_equity', 'Özkaynaklar', 'balance_sheet', 'equity'),
('XI_29', '2O', 'shareholders_equity', 'Ana Ortaklığa Ait Özkaynaklar', 'balance_sheet', 'equity'),
('XI_29', '2OA', 'paid_in_capital', 'Ödenmiş Sermaye', 'balance_sheet', 'equity'),
('XI_29', '2OCF', 'retained_earnings', 'Dönem Net Kar/Zararı', 'balance_sheet', 'equity'),
('XI_29', '2OCE', 'retained_earnings', 'Geçmiş Yıllar Kar/Zararları', 'balance_sheet', 'equity'),
('XI_29', '3C', 'revenue', 'Satış Gelirleri', 'income_statement', 'revenue'),
('XI_29', '3CA', 'cost_of_goods_sold', 'Satışların Maliyeti', 'income_statement', 'expense'),
('XI_29', '3CAB', 'gross_profit', 'Brüt Kar (Zarar)', 'income_statement', 'revenue'),
('XI_29', '3D', 'gross_profit', 'BRÜT KAR (ZARAR)', 'income_statement', 'revenue'),
('XI_29', '3DF', 'operating_income', 'FAALİYET KARI (ZARARI)', 'income_statement', 'revenue'),
('XI_29', '3H', 'operating_income', 'Net Faaliyet Kar/Zararı', 'income_statement', 'revenue'),
('XI_29', '3HB', 'financial_income', 'Finansal Gelirler', 'income_statement', 'revenue'),
('XI_29', '3HC', 'financial_expense', 'Finansal Giderler', 'income_statement', 'expense'),
('XI_29', '3I', 'profit_before_tax', 'Vergi Öncesi Kar', 'income_statement', 'revenue'),
('XI_29', '3J', 'net_income_continuing', 'Sürdürülen Faaliyetler Dönem Karı', 'income_statement', 'revenue'),
('XI_29', '3L', 'net_income', 'DÖNEM KARI (ZARARI)', 'income_statement', 'revenue'),
('XI_29', '3Z', 'net_income', 'Ana Ortaklık Payları', 'income_statement', 'revenue'),
('XI_29', '4C', 'operating_cash_flow', 'İşletme Faaliyetlerinden Nakit', 'cash_flow', 'operating'),
('XI_29', '4CAB', 'depreciation_amortization', 'Amortisman ve İtfa Payları', 'cash_flow', 'operating'),
('XI_29', '4CB', 'free_cash_flow', 'Serbest Nakit Akım', 'cash_flow', 'operating'),
('UFRS_K', '1Z', 'total_assets', 'Toplam Aktifler', 'balance_sheet', 'asset'),
('UFRS_K', '1A', 'cash_and_cb', 'Nakit ve Merkez Bankası', 'balance_sheet', 'asset'),
('UFRS_K', '1AC', 'banks_correspondent', 'Muhabir Bankalar', 'balance_sheet', 'asset'),
('UFRS_K', '1AF', 'gross_loans', 'Brüt Krediler', 'balance_sheet', 'asset'),
('UFRS_K', '1AFD', 'non_performing_loans', 'Takipteki Krediler', 'balance_sheet', 'asset'),
('UFRS_K', '1AL', 'finance_lease_receivables', 'Finansal Kiralama Alacakları', 'balance_sheet', 'asset'),
('UFRS_K', '1AN', 'tangible_assets', 'Maddi Duran Varlıklar', 'balance_sheet', 'asset'),
('UFRS_K', '1AO', 'intangible_assets', 'Maddi Olmayan Duran Varlıklar', 'balance_sheet', 'asset'),
('UFRS_K', '1AR', 'tax_assets', 'Vergi Varlıkları', 'balance_sheet', 'asset'),
('UFRS_K', '2Z', 'total_liabilities_equity', 'Toplam Kaynaklar', 'balance_sheet', 'liability'),
('UFRS_K', '2A', 'deposits', 'Mevduat', 'balance_sheet', 'liability'),
('UFRS_K', '2C', 'borrowed_funds', 'Alınan Krediler', 'balance_sheet', 'liability'),
('UFRS_K', '2D', 'money_market_funds', 'Para Piyasası Borçları', 'balance_sheet', 'liability'),
('UFRS_K', '2L', 'provisions', 'Karşılıklar', 'balance_sheet', 'liability'),
('UFRS_K', '2M', 'tax_liabilities', 'Vergi Yükümlülükleri', 'balance_sheet', 'liability'),
('UFRS_K', '2NBA', 'subordinated_debt', 'Sermaye Benzeri Krediler', 'balance_sheet', 'liability'),
('UFRS_K', '2O', 'shareholders_equity', 'Özkaynaklar', 'balance_sheet', 'equity'),
('UFRS_K', '2OV', 'period_net_income', 'Dönem Net Karı', 'balance_sheet', 'equity'),
('UFRS_K', '2OVA', 'minority_interests', 'Azınlık Payları', 'balance_sheet', 'equity'),
('UFRS_K', '3A', 'interest_income', 'Faiz Gelirleri', 'income_statement', 'revenue'),
('UFRS_K', '3B', 'interest_expense', 'Faiz Giderleri', 'income_statement', 'expense'),
('UFRS_K', '3C', 'net_interest_income', 'Net Faiz Geliri', 'income_statement', 'revenue'),
('UFRS_K', '3CA', 'net_commission_income', 'Net Ücret ve Komisyon Geliri', 'income_statement', 'revenue'),
('UFRS_K', '3CAA', 'commission_income', 'Alınan Komisyonlar', 'income_statement', 'revenue'),
('UFRS_K', '3CAD', 'commission_expense', 'Verilen Komisyonlar', 'income_statement', 'expense'),
('UFRS_K', '3CB', 'dividend_income', 'Temettü Gelirleri', 'income_statement', 'revenue'),
('UFRS_K', '3CC', 'trading_income', 'Ticari Kar/Zarar', 'income_statement', 'revenue'),
('UFRS_K', '3CD', 'other_operating_income', 'Diğer Faaliyet Gelirleri', 'income_statement', 'revenue'),
('UFRS_K', '3CE', 'operating_expenses', 'Faaliyet Giderleri', 'income_statement', 'expense'),
('UFRS_K', '3CF', 'total_operating_income', 'Toplam Faaliyet Geliri', 'income_statement', 'revenue'),
('UFRS_K', '3L', 'net_income', 'Dönem Net Karı', 'income_statement', 'revenue'),
('UFRS_F', '1Z', 'total_assets', 'Toplam Aktifler', 'balance_sheet', 'asset'),
('UFRS_F', '1A', 'cash_and_cb', 'Nakit ve Merkez Bankası', 'balance_sheet', 'asset'),
('UFRS_F', '1AC', 'banks_correspondent', 'Muhabir Bankalar', 'balance_sheet', 'asset'),
('UFRS_F', '1AF', 'gross_loans', 'Brüt Krediler', 'balance_sheet', 'asset'),
('UFRS_F', '1AFD', 'non_performing_loans', 'Takipteki Krediler', 'balance_sheet', 'asset'),
('UFRS_F', '1AL', 'finance_lease_receivables', 'Finansal Kiralama Alacakları', 'balance_sheet', 'asset'),
('UFRS_F', '1AN', 'tangible_assets', 'Maddi Duran Varlıklar', 'balance_sheet', 'asset'),
('UFRS_F', '1AO', 'intangible_assets', 'Maddi Olmayan Duran Varlıklar', 'balance_sheet', 'asset'),
('UFRS_F', '1AR', 'tax_assets', 'Vergi Varlıkları', 'balance_sheet', 'asset'),
('UFRS_F', '2Z', 'total_liabilities_equity', 'Toplam Kaynaklar', 'balance_sheet', 'liability'),
('UFRS_F', '2A', 'deposits', 'Mevduat', 'balance_sheet', 'liability'),
('UFRS_F', '2C', 'borrowed_funds', 'Alınan Krediler', 'balance_sheet', 'liability'),
('UFRS_F', '2D', 'money_market_funds', 'Para Piyasası Borçları', 'balance_sheet', 'liability'),
('UFRS_F', '2L', 'provisions', 'Karşılıklar', 'balance_sheet', 'liability'),
('UFRS_F', '2M', 'tax_liabilities', 'Vergi Yükümlülükleri', 'balance_sheet', 'liability'),
('UFRS_F', '2NBA', 'subordinated_debt', 'Sermaye Benzeri Krediler', 'balance_sheet', 'liability'),
('UFRS_F', '2O', 'shareholders_equity', 'Özkaynaklar', 'balance_sheet', 'equity'),
('UFRS_F', '2OV', 'period_net_income', 'Dönem Net Karı', 'balance_sheet', 'equity'),
('UFRS_F', '2OVA', 'minority_interests', 'Azınlık Payları', 'balance_sheet', 'equity'),
('UFRS_F', '3A', 'interest_income', 'Faiz Gelirleri', 'income_statement', 'revenue'),
('UFRS_F', '3B', 'interest_expense', 'Faiz Giderleri', 'income_statement', 'expense'),
('UFRS_F', '3C', 'net_interest_income', 'Net Faiz Geliri', 'income_statement', 'revenue'),
('UFRS_F', '3CA', 'net_commission_income', 'Net Ücret ve Komisyon Geliri', 'income_statement', 'revenue'),
('UFRS_F', '3CAA', 'commission_income', 'Alınan Komisyonlar', 'income_statement', 'revenue'),
('UFRS_F', '3CAD', 'commission_expense', 'Verilen Komisyonlar', 'income_statement', 'expense'),
('UFRS_F', '3CB', 'dividend_income', 'Temettü Gelirleri', 'income_statement', 'revenue'),
('UFRS_F', '3CC', 'trading_income', 'Ticari Kar/Zarar', 'income_statement', 'revenue'),
('UFRS_F', '3CD', 'other_operating_income', 'Diğer Faaliyet Gelirleri', 'income_statement', 'revenue'),
('UFRS_F', '3CE', 'operating_expenses', 'Faaliyet Giderleri', 'income_statement', 'expense'),
('UFRS_F', '3CF', 'total_operating_income', 'Toplam Faaliyet Geliri', 'income_statement', 'revenue'),
('UFRS_F', '3L', 'net_income', 'Dönem Net Karı', 'income_statement', 'revenue'),
('UFRS_S', '1Z', 'total_assets', 'Toplam Aktifler', 'balance_sheet', 'asset'),
('UFRS_S', '1A', 'cash_and_cb', 'Nakit ve Merkez Bankası', 'balance_sheet', 'asset'),
('UFRS_S', '1AC', 'banks_correspondent', 'Muhabir Bankalar', 'balance_sheet', 'asset'),
('UFRS_S', '1AF', 'gross_loans', 'Brüt Krediler', 'balance_sheet', 'asset'),
('UFRS_S', '1AFD', 'non_performing_loans', 'Takipteki Krediler', 'balance_sheet', 'asset'),
('UFRS_S', '1AL', 'finance_lease_receivables', 'Finansal Kiralama Alacakları', 'balance_sheet', 'asset'),
('UFRS_S', '1AN', 'tangible_assets', 'Maddi Duran Varlıklar', 'balance_sheet', 'asset'),
('UFRS_S', '1AO', 'intangible_assets', 'Maddi Olmayan Duran Varlıklar', 'balance_sheet', 'asset'),
('UFRS_S', '1AR', 'tax_assets', 'Vergi Varlıkları', 'balance_sheet', 'asset'),
('UFRS_S', '2Z', 'total_liabilities_equity', 'Toplam Kaynaklar', 'balance_sheet', 'liability'),
('UFRS_S', '2A', 'deposits', 'Mevduat', 'balance_sheet', 'liability'),
('UFRS_S', '2C', 'borrowed_funds', 'Alınan Krediler', 'balance_sheet', 'liability'),
('UFRS_S', '2D', 'money_market_funds', 'Para Piyasası Borçları', 'balance_sheet', 'liability'),
('UFRS_S', '2L', 'provisions', 'Karşılıklar', 'balance_sheet', 'liability'),
('UFRS_S', '2M', 'tax_liabilities', 'Vergi Yükümlülükleri', 'balance_sheet', 'liability'),
('UFRS_S', '2NBA', 'subordinated_debt', 'Sermaye Benzeri Krediler', 'balance_sheet', 'liability'),
('UFRS_S', '2O', 'shareholders_equity', 'Özkaynaklar', 'balance_sheet', 'equity'),
('UFRS_S', '2OV', 'period_net_income', 'Dönem Net Karı', 'balance_sheet', 'equity'),
('UFRS_S', '2OVA', 'minority_interests', 'Azınlık Payları', 'balance_sheet', 'equity'),
('UFRS_S', '3A', 'interest_income', 'Faiz Gelirleri', 'income_statement', 'revenue'),
('UFRS_S', '3B', 'interest_expense', 'Faiz Giderleri', 'income_statement', 'expense'),
('UFRS_S', '3C', 'net_interest_income', 'Net Faiz Geliri', 'income_statement', 'revenue'),
('UFRS_S', '3CA', 'net_commission_income', 'Net Ücret ve Komisyon Geliri', 'income_statement', 'revenue'),
('UFRS_S', '3CAA', 'commission_income', 'Alınan Komisyonlar', 'income_statement', 'revenue'),
('UFRS_S', '3CAD', 'commission_expense', 'Verilen Komisyonlar', 'income_statement', 'expense'),
('UFRS_S', '3CB', 'dividend_income', 'Temettü Gelirleri', 'income_statement', 'revenue'),
('UFRS_S', '3CC', 'trading_income', 'Ticari Kar/Zarar', 'income_statement', 'revenue'),
('UFRS_S', '3CD', 'other_operating_income', 'Diğer Faaliyet Gelirleri', 'income_statement', 'revenue'),
('UFRS_S', '3CE', 'operating_expenses', 'Faaliyet Giderleri', 'income_statement', 'expense'),
('UFRS_S', '3CF', 'total_operating_income', 'Toplam Faaliyet Geliri', 'income_statement', 'revenue'),
('UFRS_S', '3L', 'net_income', 'Dönem Net Karı', 'income_statement', 'revenue');
